healthdata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('healthrecords.urls'))
]

healthrecords/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('patients-data/', views.patient, name='patient'),
    path('about/', views.about, name='about')
]

healthrecords/models.py
from django.db import models

# Create your models here.

healthrecords/forms.py
from django import forms


class PatientForm(forms.Form):
    sodium = forms.FloatField(label='Sodium (mEq/L)', initial=140)
    temp = forms.FloatField(label='Temperature (C)', initial=37)
    creatinine = forms.FloatField(label='Creatinine (mg/dL)', initial=1)
    bilirubin = forms.FloatField(label='Bilirubin (mg/dL)', initial=1)
    albumin = forms.FloatField(label='Albumin (g/L)', initial=40)
    arterial_ph = forms.FloatField(label='Arterial pH', initial=7.4)
    arterial_po = forms.FloatField(label='Arterial pO2 (mmHg)', initial=90)
    heartrate = forms.FloatField(label='HeartRate (/min)', initial=80)
    wbc = forms.FloatField(label='WBC (x1000/mm3)', initial=10)
    paofio = forms.FloatField(label='PAO FiO2 (%)')
    resperate = forms.FloatField(label='Resperate')
    potassium = forms.FloatField(label='Potassium')
    platelets = forms.FloatField(label='Platelets')
    lactate = forms.FloatField(label='Lactate')
    hemoglobin = forms.FloatField(label='Hemoglobin')
    glucose = forms.FloatField(label='Glucose')
    calcium = forms.FloatField(label='Calcium')

    # sodium_a = forms.FloatField(label='Sodium (mEq/L)', initial=140)
    # sodium_h= forms.FloatField(label='Sodium (mEq/L)', initial=140)
    # sodium_d= forms.FloatField(label='Sodium (mEq/L)', initial=140)
    # temp_a = forms.FloatField(label='Temperature (C)', initial=37)
    # temp_h = forms.FloatField(label='Temperature (C)', initial=37)
    # temp_d = forms.FloatField(label='Temperature (C)', initial=37)
    # creatinine_a = forms.FloatField(label='Creatinine (mg/dL)', initial=1)
    # creatinine_h = forms.FloatField(label='Creatinine (mg/dL)', initial=1)
    # creatinine_d = forms.FloatField(label='Creatinine (mg/dL)', initial=1)
    # bilirubin_a = forms.FloatField(label='Bilirubin (mg/dL)', initial=1)
    # bilirubin_h = forms.FloatField(label='Bilirubin (mg/dL)', initial=1)
    # bilirubin_d = forms.FloatField(label='Bilirubin (mg/dL)', initial=1)
    # albumin_a = forms.FloatField(label='Albumin (g/L)', initial=40)
    # albumin_h = forms.FloatField(label='Albumin (g/L)', initial=40)
    # albumin_d = forms.FloatField(label='Albumin (g/L)', initial=40)
    # arterial_ph_a = forms.FloatField(label='Arterial pH', initial=7.4)
    # arterial_ph_h = forms.FloatField(label='Arterial pH', initial=7.4)
    # arterial_ph_d = forms.FloatField(label='Arterial pH', initial=7.4)
    # arterial_po_a = forms.FloatField(label='Arterial pO2 (mmHg)', initial=90)
    # arterial_po_h = forms.FloatField(label='Arterial pO2 (mmHg)', initial=90)
    # arterial_po_d = forms.FloatField(label='Arterial pO2 (mmHg)', initial=90)
    # heartrate_a = forms.FloatField(label='HeartRate (/min)', initial=80)
    # heartrate_h = forms.FloatField(label='HeartRate (/min)', initial=80)
    # heartrate_d = forms.FloatField(label='HeartRate (/min)', initial=80)
    # wbc_a = forms.FloatField(label='WBC (x1000/mm3)', initial=10)
    # wbc_h = forms.FloatField(label='WBC (x1000/mm3)', initial=10)
    # wbc_d = forms.FloatField(label='WBC (x1000/mm3)', initial=10)
    # paofio_a = forms.FloatField(label='PAO FiO2 (%)')
    # paofio_h = forms.FloatField(label='PAO FiO2 (%)')
    # paofio_d = forms.FloatField(label='PAO FiO2 (%)')
    # resperate_a = forms.FloatField(label='Resperate')
    # resperate_h = forms.FloatField(label='Resperate')
    # resperate_d = forms.FloatField(label='Resperate')
    # potassium_a = forms.FloatField(label='Potassium')
    # potassium_h = forms.FloatField(label='Potassium')
    # potassium_d = forms.FloatField(label='Potassium')
    # platelets_a = forms.FloatField(label='Platelets')
    # platelets_h = forms.FloatField(label='Platelets')
    # platelets_d = forms.FloatField(label='Platelets')
    # lactate_a = forms.FloatField(label='Lactate')
    # lactate_h = forms.FloatField(label='Lactate')
    # lactate_d = forms.FloatField(label='Lactate')
    # hemoglobin_a = forms.FloatField(label='Hemoglobin')
    # hemoglobin_h = forms.FloatField(label='Hemoglobin')
    # hemoglobin_d = forms.FloatField(label='Hemoglobin')
    # glucose_a = forms.FloatField(label='Glucose')
    # glucose_h = forms.FloatField(label='Glucose')
    # glucose_d = forms.FloatField(label='Glucose')
    # calcium_a = forms.FloatField(label='Calcium')
    # calcium_h = forms.FloatField(label='Calcium')
    # calcium_d = forms.FloatField(label='Calcium')
    #
    # def clean(self):
    #     pass
    
     # class SymptomWidget(forms.MultiWidget):
#     def __init__(self, *args, **kwargs):
#         super(SymptomWidget, self).__init__(*args, **kwargs,
#         widgets = [
#             forms.IntegerField(),
#             forms.IntegerField(),
#             forms.IntegerField()
#         ])
#
#     def decompress(self, value):
#         if value:
#             return value.split(' ')
#         return [None, None]
#
#
# class SymptomField(forms.MultiValueField):
#     widget = SymptomWidget
#
#     def __init__(self, label=None, initial=None):
#         super(SymptomField, self).__init__(label=label, initial=initial,
#         fields = (
#             forms.IntegerField(initial=initial, label='Apache'),
#             forms.IntegerField(initial=initial, label='Hour 1'),
#             forms.IntegerField(initial=initial, label='Day 1')
#         ))
#
#     def compress(self, data_list):
#         return ' '.join(data_list)
#
#
# class PatientForm(forms.ModelForm):
#     sodium = SymptomField(label='Sodium (mEq/L)', initial=140)
#     temp = SymptomField(label='Temperature (C)', initial=37)
#     creatinine = SymptomField(label='Creatinine (mg/dL)', initial=1)
#     bilirubin = SymptomField(label='Bilirubin (mg/dL)', initial=1)
#     albumin = SymptomField(label='Albumin (g/L)', initial=40)
#     arterial_ph = SymptomField(label='Arterial pH', initial=7.4)
#     arterial_po = SymptomField(label='Arterial pO2 (mmHg)', initial=90)
#     heartrate = SymptomField(label='HeartRate (/min)', initial=80)
#     wbc = SymptomField(label='WBC (x1000/mm3)', initial=10)
#     paofio = SymptomField(label='PAO FiO2 (%)')
#     resperate = SymptomField(label='Resperate')
#     potassium = SymptomField(label='Potassium')
#     platelets = SymptomField(label='Platelets')
#     lactate = SymptomField(label='Lactate')
#     hemoglobin = SymptomField(label='Hemoglobin')
#     glucose = SymptomField(label='Glucose')
#     calcium = SymptomField(label='Calcium')

def validate_file_extension(f):
    if not f.name.endswith('.csv'):
        raise forms.ValidationError("Must be a CSV file.")

class CSVForm(forms.Form):
    file = forms.FileField(validators=[validate_file_extension])

healthrecords/views.py
from django.shortcuts import render, HttpResponse
from healthrecords.forms import PatientForm, CSVForm
from healthrecords.gossis_models.imputation import impute_csv
from healthrecords.gossis_models.csv_upload_preprocess import summarize


# Create your views here.
def index(request):
    if request.method == 'POST':
        form = CSVForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            imputed_db = impute_csv(r"C:\Users\Tyrone\PycharmProjects\healthdata\healthrecords\gossis_models\xgb_bin", file)
            upload_title, upload_summary = summarize(file, "upload")
            imputation_title, imputation_summary = summarize(imputed_db, "imputation")
            html_db = imputed_db.to_html()
            # Make the data passing more discrete
            return render(request, 'healthrecords/input_data_process.html', {'table_title': "Imputed Database", 'html_file': html_db, 'upload_summary': upload_summary, 'upload_title': upload_title, 'imputation_summary': imputation_summary, 'imputation_title': imputation_title})
            # return render(request, 'healthrecords/patients-data.html', {'inputted_data': form.cleaned_data})  # form.cleaned_data is a dictionary
    else:
        form = CSVForm()
    return render(request, 'healthrecords/index.html', {'form': form})

    # if request.method == 'POST':
    #     form = PatientForm(request.POST)
    #     csvform = CSVForm()
    #     if csvform.is_valid():
    #         return HttpResponse("Nice job!")
    #         # return render(request, 'healthrecords/patients-data.html', {'inputted_data': form.cleaned_data})
    #     else:
    #         return render(request, 'healthrecords/index.html', {'form': form, 'csvform': csvform})
    # else:
    #     form = PatientForm()
    #     csvform = CSVForm()
    #     return render(request, 'healthrecords/index.html', {'form': form, 'csvform': csvform})


def contact(request):
    return render(request, 'healthrecords/contact.html')

def patient(request):
    return HttpResponse("Form submitted correctly")

def about(request):
    return render(request, 'healthrecords/about.html')

templates/healthrecords/about.html
{% extends "healthrecords/header.html" %}

{% block content %}
    <p>This is the about page.</p>
{% endblock %}

templates/healthrecords/contact.html
{% extends "healthrecords/header.html" %}

{% block content %}
    <div class="card" style="width: 18rem;">
        {% load static %}
        <img src="{% static "healthrecords/img/jesse_raffa_110x110_0.jpg" %}" class="card-img-top" alt="face">
        <div class="card-body">
            <p class="card-text">
                Dr. Jesse Raffa <br>
                Email: <a href="mailto:jraffa@mit.edu">jraffa@mit.edu</a>
            </p>
        </div>
    </div>
{% endblock %}

templates/healthrecords/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>GOSSIS</title>
    <meta charset="utf-8"/>
    {% load static %}
    {#        <link rel="stylesheet" href="{% static "healthrecords/css/bootstrap.css/bootstrap.min.css" %}" type="text/css"/>#}
    {#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">#}
    {#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'healthrecords/css/main.css' %}">
</head>

<body class="body">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">GOSSIS Mortality Calculator</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about/">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact/">Contact</a>
            </li>
        </ul>
    </div>
</nav>

<div class='container-fluid'>
    <br><br>
    {% block content %}
    {% endblock %}
</div>

<footer class="footer font-small">
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="/"> gossis.com</a>
    </div>
</footer>

</body>
{#<script src={% static "healthrecords/js/basicjs.js" %}></script>#}
</html>

templates/healthrecords/index.html
{% extends "healthrecords/header.html" %}

{% block content %}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        <table class="table d-md-table table-hover">#}
{#            <thead class="thead-light header-fixed">#}
{#            <tr>#}
{#                <th scope="col">Blank</th>#}
{#                <th scope="col">Apache</th>#}
{#                <th scope="col">Hour 1</th>#}
{#                <th scope="col">Day 1</th>#}
{#            </tr>#}
{#            </thead>#}
{#            <tbody>#}
{#            {% for field in form %}#}
{#                <tr>#}
{#                    <th scope="row">{{ field.label_tag }}</th>#}
{#                    <td>{{ field }}</td>#}
{#                    <td>{{ field }}</td>#}
{#                    <td>{{ field }}</td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#            </tbody>#}
{#        </table>#}
{#        <br>#}
{#        <button type="submit" class="btn btn-primary">Calculate</button>#}
{#    </form>#}

    <h3>
    Upload a csv file with each row representing a patient and their ICU data.
    </h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <p>
                {{ form }}
            </p>
            <button type="submit" class="btn btn-primary">Upload</button>
    </form>

{% endblock %}

{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        <table class="table d-md-table table-hover">#}
{#            <thead class="thead-light header-fixed">#}
{#            <tr>#}
{#                <th scope="col">Blank</th>#}
{#                <th scope="col">Apache</th>#}
{#                <th scope="col">Hour 1</th>#}
{#                <th scope="col">Day 1</th>#}
{#            </tr>#}
{#            </thead>#}
{#            <tbody>#}
{#            <tr>#}
{#                <th><label for="id_sodium">Sodium (mEq/L):</label></th>#}
{#                <td><input type="number" name="sodium" value="140" step="any" required id="id_sodium"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_temp">Temperature (C):</label></th>#}
{#                <td><input type="number" name="temp" value="37" step="any" required id="id_temp"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_creatinine">Creatinine (mg/dL):</label></th>#}
{#                <td><input type="number" name="creatinine" value="1" step="any" required id="id_creatinine"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_bilirubin">Bilirubin (mg/dL):</label></th>#}
{#                <td><input type="number" name="bilirubin" value="1" step="any" required id="id_bilirubin"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_albumin">Albumin (g/L):</label></th>#}
{#                <td><input type="number" name="albumin" value="40" step="any" required id="id_albumin"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_arterial_ph">Arterial pH:</label></th>#}
{#                <td><input type="number" name="arterial_ph" value="7.4" step="any" required id="id_arterial_ph"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_arterial_po">Arterial pO2 (mmHg):</label></th>#}
{#                <td><input type="number" name="arterial_po" value="90" step="any" required id="id_arterial_po"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_heartrate">HeartRate (/min):</label></th>#}
{#                <td><input type="number" name="heartrate" value="80" step="any" required id="id_heartrate"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_wbc">WBC (x1000/mm3):</label></th>#}
{#                <td><input type="number" name="wbc" value="10" step="any" required id="id_wbc"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_paofio">PAO FiO2 (%):</label></th>#}
{#                <td><input type="number" name="paofio" step="any" required id="id_paofio"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_resperate">Resperate:</label></th>#}
{#                <td><input type="number" name="resperate" step="any" required id="id_resperate"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_potassium">Potassium:</label></th>#}
{#                <td><input type="number" name="potassium" step="any" required id="id_potassium"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_platelets">Platelets:</label></th>#}
{#                <td><input type="number" name="platelets" step="any" required id="id_platelets"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_lactate">Lactate:</label></th>#}
{#                <td><input type="number" name="lactate" step="any" required id="id_lactate"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_hemoglobin">Hemoglobin:</label></th>#}
{#                <td><input type="number" name="hemoglobin" step="any" required id="id_hemoglobin"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_glucose">Glucose:</label></th>#}
{#                <td><input type="number" name="glucose" step="any" required id="id_glucose"></td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th><label for="id_calcium">Calcium:</label></th>#}
{#                <td><input type="number" name="calcium" step="any" required id="id_calcium"></td>#}
{#            </tr>#}
{#            </tbody>#}
{#        </table>#}
{#        <br>#}
{#        <button type="submit" class="btn btn-primary">Calculate</button>#}
{#    </form>#}
{#{% endblock %}#}

templates/healthrecords/input_data_process.html
{% extends "healthrecords/header.html" %}

{% block content %}
    <h3> {{ upload_title }} </h3>
    {% for label, value in upload_summary.items %}
        {{ label }}: {{ value }}
        <br>
    {% endfor %}
    <h3> {{ imputation_title }} </h3>
    {% for label, value in imputation_summary.items %}
        {{ label }}: {{ value }}
        <br>
    {% endfor %}
    <br>
    {{ table_title }}
    {{ html_file }}
{% endblock %}

templates/healthrecords/patients-data.html
{% extends "healthrecords/header.html" %}

{% block content %}
    {% for label, value in inputted_data.items %}
        {{ label }}: {{ value }}
        <br>
    {% endfor %}
{% endblock %}